import * as fs from 'fs';
import * as path from 'path';
import type { Reporter, TestCase, TestResult, FullResult, Suite, FullConfig } from '@playwright/test/reporter';

const RESULTS_ROOT = path.join(process.cwd(), 'testing', 'results');

interface BugInfo {
  testName: string;
  suiteName: string;
  error: string;
  duration: number;
}

class ExpeditoReporter implements Reporter {
  private runId: string;
  private runFolder: string;
  private passed: number = 0;
  private failed: number = 0;
  private bugs: BugInfo[] = [];
  private startTime: Date;

  constructor() {
    this.startTime = new Date();
    this.runId = this.startTime.toISOString().replace(/[:.]/g, '-').split('T').join('_');
    this.runFolder = path.join(RESULTS_ROOT, `RUN_${this.runId}`);
    
    if (!fs.existsSync(this.runFolder)) {
      fs.mkdirSync(this.runFolder, { recursive: true });
    }
    
    console.log(`\n🚀 Expeditoo QA Test Run Started`);
    console.log(`📁 Results will be saved to: ${this.runFolder}\n`);
  }

  onTestEnd(test: TestCase, result: TestResult) {
    if (result.status === 'passed') {
      this.passed++;
    } else if (result.status === 'failed' || result.status === 'timedOut') {
      this.failed++;
      
      // Capture bug info
      this.bugs.push({
        testName: test.title,
        suiteName: test.parent.title,
        error: result.error?.message || 'Unknown error',
        duration: result.duration
      });

      // Save screenshot if available
      for (const attachment of result.attachments) {
        if (attachment.name === 'screenshot' && attachment.path) {
          const destPath = path.join(this.runFolder, `${test.title.replace(/[^a-z0-9]/gi, '_')}.png`);
          try {
            fs.copyFileSync(attachment.path, destPath);
          } catch (e) {
            // Attachment might not exist
          }
        }
      }
    }
  }

  onEnd(result: FullResult) {
    const endTime = new Date();
    const duration = (endTime.getTime() - this.startTime.getTime()) / 1000;

    const summaryMd = `
# 🧪 EXPEDITOO TEST EXECUTION SUMMARY

| Info | Value |
|------|-------|
| **Run ID** | \`${this.runId}\` |
| **Started** | ${this.startTime.toLocaleString()} |
| **Duration** | ${duration.toFixed(1)}s |
| **Status** | ${result.status.toUpperCase()} |

## 📊 Results

| Metric | Count |
|--------|-------|
| **Total Tests** | ${this.passed + this.failed} |
| ✅ **Passed** | ${this.passed} |
| ❌ **Failed** | ${this.failed} |

${this.bugs.length === 0 ? '\n## 🎉 All Tests Passed!\n\nNo defects found. Great job!\n' : ''}

${this.bugs.length > 0 ? `
## 🐛 Defects Found (${this.bugs.length})

${this.bugs.map((bug, i) => `
### ${i + 1}. [${bug.suiteName}] ${bug.testName}
- **Duration:** ${(bug.duration / 1000).toFixed(1)}s
- **Error:** \`${bug.error.substring(0, 200)}\`
`).join('\n')}
` : ''}

---
*Generated by Expeditoo QA Framework*
`;

    fs.writeFileSync(path.join(this.runFolder, 'SUMMARY.md'), summaryMd);

    console.log(`\n${'='.repeat(60)}`);
    console.log(`✨ TEST RUN COMPLETE`);
    console.log(`${'='.repeat(60)}`);
    console.log(`📊 Passed: ${this.passed} | Failed: ${this.failed}`);
    console.log(`📁 Summary: ${path.join(this.runFolder, 'SUMMARY.md')}`);
    console.log(`${'='.repeat(60)}\n`);
  }
}

export default ExpeditoReporter;
